version: '2'
services:
    storeeroku-app:
        image: storeeroku
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://storeeroku-mysql:3306/storeeroku?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=storeeroku-elasticsearch:9300
        ports:
            - 8080:8080
    storeeroku-mysql:
        extends:
            file: mysql.yml
            service: storeeroku-mysql
    storeeroku-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: storeeroku-elasticsearch
